# This is free software, licensed under the Apache License, Version 2.0
#
# Copyright (C) 2026 Dante <dante@seckv.com>

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-netbird-next

LUCI_TITLE:=LuCI for NetBird
LUCI_DEPENDS:=+netbird-next
LUCI_DESCRIPTION:=LuCI support for NetBird Mesh VPN (Next)

PKG_MAINTAINER:=Dante <dante@seckv.com>
PKG_VERSION:=1.0
PKG_RELEASE:=1
PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
